### ISSUE TITLE
Internet Error

### ISSUE THREAD

**Issue by mehrdad-parsa68** [sean-ww/react-redux-datatable#61]
Hi
I run this code with thunk but when I want to load the page for a second table appear then suddenly this error appears :  The table failed to initialise. Please check you are connected to the internet and try again.

Would you please inform me?

Best regards

**Comment by sean-ww** [comment]
Hi,
You need to diagnose the underlying issue. That's just a generic error message.
If you check [the example](https://sean-ww.github.io/react-redux-datatable/demo/?selectedKind=Table%20Settings&selectedStory=Custom%20Api%20Error&full=0&addons=0&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) you can see how to handle errors. The errorObject will tell you what the issue is.
Hopefully that will solve things or at least start the process :)
